### ISSUE TITLE
[BUG] Mapping comic infinitely looping when a chapter name contains "&amp;"

### ISSUE THREAD

**Issue by bust4cap** [VandersonQk/KuroReaderReleases#29] opened 2024-10-05 11:27 UTC
**App details**
- Version: 1.6.1
- Type: Pro
- Distribuition: PlayStore
- File access mode (setting): Full

**Smartphone/Tablet:**
 - Android Version: 12
 - Device: Lenovo Tab M10 (3rd Gen)

**Describe the bug**
When a chapter name in a comicinfo.xml contains the "&" character formatted as "`&amp;`" , two page view doesnt work because mapping comic infinitely loops from 0-100% without finishing.
(having it just as "&" works for mapping comic, but it completely breaks all metadata present in a comicinfo.xml)

**To Reproduce**
1. Have a cbz including a comicinfo.xml that has a chapter name include "`&amp;`"
2. When opening the cbz to read it (either with auto map comic enabled or when putting the tablet in landscape mode when auto map comic isnt enabled) mapping comic infinitely loops from 0-100%, never finishes and two page view doesnt work

**Comment by VandersonQk** [comment] 2024-10-08 18:40
I tried to simulate this, but I couldn't reproduce the problem. I edited a file, adding chapters with a `&` in the name, and it worked as it was supposed to.
![image](https://github.com/user-attachments/assets/7ed6fb2c-3e9b-4ed9-bb28-47fe1f1b01c1)

Do you have any example files to share? If so, please upload the files to Google Drive or another service, and send the links to our email (apps @ kurotoshiro.dev). Maybe it's a different problem, not exactly related to the chapters name.

**Comment by bust4cap** [comment] 2024-10-09 10:41
Sent the mail just now.
I did rather extensive testing before submitting the bug report and that was my personal finding. with everything else being the same, just replacing `&amp;` with the word "and" fixed it

**Comment by VandersonQk** [comment] 2024-10-29 20:28
Fixed in [version 1.6.2](https://github.com/VandersonQk/KuroReaderReleases/releases/tag/v1.6.2-hotfix)

**Closed as completed by VandersonQk** 2024-10-29 20:28 UTC
